Create RHEL8 commands to pass handler using highest version test.
The failing handler.py test output:

ERROR: In `handlers/rhel8.py` the "bootloader" command maps to "F21_Bootloader" while in
`pykickstart.commands.bootloader` there is newer implementation: "RHEL7_Bootloader".

ERROR: In `handlers/rhel8.py` the "fcoe" command maps to "F13_Fcoe" while in
`pykickstart.commands.fcoe` there is newer implementation: "RHEL7_Fcoe".

ERROR: In `handlers/rhel8.py` the "ostreesetup" command maps to "F21_OSTreeSetup" while in
`pykickstart.commands.ostreesetup` there is newer implementation: "RHEL7_OSTreeSetup".

ERROR: In `handlers/rhel8.py` the "volgroup" command maps to "F21_VolGroup" while in
`pykickstart.commands.volgroup` there is newer implementation: "RHEL7_VolGroup".

ERROR: In `handlers/rhel8.py` "FcoeData" maps to "F13_FcoeData" while in
`pykickstart.commands.fcoe` there is newer implementation: "RHEL7_FcoeData".

ERROR: In `handlers/rhel8.py` "VolGroupData" maps to "F21_VolGroupData" while in
`pykickstart.commands.volgroup` there is newer implementation: "RHEL7_VolGroupData".

I was thinking whether the test should be changed instead not to take into
account the case where implementation version and handler version are both RHEL.
I don't think so. For FCoE, where the RHEL class derived from Fedora class used
in the handler the test actually revealed that the RHEL implementation was not
added to Fedora. Which is good and I will have to add it.

For other cases (eg Bootloader), the RHEL class is subclassing Fedora one
without actually adding any implementation.

class RHELX(FedoraY):
   pass

Which has probably historical reasons (Rebase to F21 in RHEL7?) . I think we
generally subclass RHEL version from Fedora only when we add something new for
RHEL, otherwise we use Fedora command in RHEL handler.

The downside of my solution is carrying on the noop subclassing to next RHEL,
but I think we can live with that and this legacy would disappear if the Fedora
command gets some update since it has been subclassed to RHEL.